# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Farma < Formula
  desc "farma is a Farcaster notification server."
  homepage "https://github.com/vrypan/farma"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/farma/releases/download/v0.0.6/farma_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "56c17045cd7fdb118b6a8f588dfa3776f45131ebddc95030331209ab4c8e44de"

      def install
        bin.install "farma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/farma/releases/download/v0.0.6/farma_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "a6fdfb90d3bd18f804884840f54f47f1f8fb336c0da817547473e58bf0edaafd"

      def install
        bin.install "farma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/farma/releases/download/v0.0.6/farma_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "8351a4d8e82040bd4239e3f2424c161000736e387c18ba8726c9eec0050971d1"

        def install
          bin.install "farma"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/farma/releases/download/v0.0.6/farma_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "268b46fe7ef2cf80f0b769e03862682da72707b10b6d85eb0f42dadd57595507"

        def install
          bin.install "farma"
        end
      end
    end
  end

  def caveats
    <<~EOS
      farma --help
    EOS
  end

  test do
    system "#{bin}/farma version"
  end
end
