# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Farma < Formula
  desc "farma is a Farcaster notification server."
  homepage "https://github.com/vrypan/farma"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vrypan/farma/releases/download/v0.6.2/farma_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "a69f59baedee04ef206149867dbca357ad32c4cb268d903557dbb5930f58a818"

      def install
        bin.install "farma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vrypan/farma/releases/download/v0.6.2/farma_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "19d521587d586e5212c8e955cd8d07d35292dd0069937cecbf2eeb673c571d69"

      def install
        bin.install "farma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/farma/releases/download/v0.6.2/farma_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "6c9e700711b37354a81da8d44f50213a96a42232b2f31beb73859f392b0f87fd"

        def install
          bin.install "farma"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/farma/releases/download/v0.6.2/farma_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "36ac39d85d5c345bfd372ff6e14770f6925cc65e47e726affed2db1f4026cfab"

        def install
          bin.install "farma"
        end
      end
    end
  end

  def caveats
    <<~EOS
      farma --help
    EOS
  end

  test do
    system "#{bin}/farma version"
  end
end
